-- auto Generated on 2019-08-13
-- DROP TABLE IF EXISTS book;
CREATE TABLE book(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	author VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'author',
	price DECIMAL (13,4) NOT NULL DEFAULT -1 COMMENT 'price',
	content VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'content',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'book';
