package com.example.provider.dto;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_zmx
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   账户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.b_time
     *
     * @mbg.generated
     */
    private Date bTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.u_type
     *
     * @mbg.generated
     */
    private Integer uType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_zmx.u_level
     *
     * @mbg.generated
     */
    private Integer uLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.id
     *
     * @return the value of user_zmx.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.id
     *
     * @param id the value for user_zmx.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.user_name
     *
     * @return the value of user_zmx.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.user_name
     *
     * @param userName the value for user_zmx.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.password
     *
     * @return the value of user_zmx.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.password
     *
     * @param password the value for user_zmx.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.b_time
     *
     * @return the value of user_zmx.b_time
     *
     * @mbg.generated
     */
    public Date getbTime() {
        return bTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.b_time
     *
     * @param bTime the value for user_zmx.b_time
     *
     * @mbg.generated
     */
    public void setbTime(Date bTime) {
        this.bTime = bTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.u_type
     *
     * @return the value of user_zmx.u_type
     *
     * @mbg.generated
     */
    public Integer getuType() {
        return uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.u_type
     *
     * @param uType the value for user_zmx.u_type
     *
     * @mbg.generated
     */
    public void setuType(Integer uType) {
        this.uType = uType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_zmx.u_level
     *
     * @return the value of user_zmx.u_level
     *
     * @mbg.generated
     */
    public Integer getuLevel() {
        return uLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_zmx.u_level
     *
     * @param uLevel the value for user_zmx.u_level
     *
     * @mbg.generated
     */
    public void setuLevel(Integer uLevel) {
        this.uLevel = uLevel;
    }
}